### ISSUE TITLE
Question 19: Remove Nth Node from end of Linked List

### ISSUE THREAD

**Issue by Aratrik-02** [Vanshika2063/Leetcode-Questions#115]
Hey @Vanshika2063, I would like to provide an implementation for this problem using fast and slow pointers in C++ would you please assign me this issue?!

**Comment by Vanshika2063** [comment]
sure

**Comment by Aratrik-02** [comment]
Hey @Vanshika2063 I have addressed this issue in #138

**Comment by Agarwalsahil** [comment]
hey @Vanshika2063 I would like to provide a solution for this problem. Would you please assign this issue to me?
