### ISSUE TITLE
remove duplicate file

### ISSUE THREAD

**Issue by Vanshika2063** [Vanshika2063/Leetcode-Questions#127]
# Can anyone remove duplicate file in easy folder

**Comment by ManasviGoyal** [comment]
Yes. I would like to contribute

**Comment by Vanshika2063** [comment]
okay

**Comment by ManasviGoyal** [comment]
@Vanshika2063 yes

**Comment by ManasviGoyal** [comment]
If there are same problems solved in different languages should I keep them?
