### ISSUE TITLE
Attached issues

### ISSUE THREAD

**Issue by Vanshika2063** [Vanshika2063/Leetcode-Questions#149]
Please contributers attached your issues in your PRs

**Comment by Vanshika2063** [comment]
> Hey @Vanshika2063 can you elaborate what we need to do?

look [CONTRIBUTING.MD](https://github.com/Vanshika2063/Leetcode-Questions/blob/main/CONTRIBUTING.md)

**Comment by AshishSharma1203** [comment]
So, do we just need to add issues from our side? In other words, we have to add more number of questions in respective sections.
