### ISSUE TITLE
LC medium addition

### ISSUE THREAD

**Issue by chiragxarora** [Vanshika2063/Leetcode-Questions#153]
I would like to add LC 36 that is valid sudoku and LC 38 that is count and say to your repo.
Please add hacktoberfest tags

**Comment by Vanshika2063** [comment]
okay!
 but not in cpp

**Comment by piyush362** [comment]
I would like to add some medium problems of leetcode

**Comment by Vanshika2063** [comment]
sure 
Attached your issues in PR

**Comment by piyush362** [comment]
i have make pr for this
