### ISSUE TITLE
Count Bad Pairs Leet Code medium 

### ISSUE THREAD

**Issue by AbhishekCS3459** [Vanshika2063/Leetcode-Questions#155]
Hey I want to add the solution for the above problem. 

![Screenshot 2022-10-03 165636](https://user-images.githubusercontent.com/94506000/193565969-5c2140ea-7da7-460f-abd3-8c364779d284.png)

**Comment by AbhishekCS3459** [comment]
**Hey please assign me to contribute for the above problem**

**Comment by Vanshika2063** [comment]
sure
Attached your issues in PR
