### ISSUE TITLE
LeetCode Binary Tree Questions

### ISSUE THREAD

**Issue by neolia-monu** [Vanshika2063/Leetcode-Questions#215]
.98. Validate Binary Search Tree
.112. Path Sum

**Comment by Vanshika2063** [comment]
sure

**Comment by satyamgupta461** [comment]
Hey, @neolia-monu  I have quite a good hands-on knowledge of JAVA and I have done this Path Sum code. Please appoint me to the project.

**Comment by Aratrik-02** [comment]
Hey @Vanshika2063 I added a code on binary tree in #243

**Comment by neolia-monu** [comment]
@satyamgupta461  Okay

**Comment by i-m-alok** [comment]
Are we looking for Java solutions only or we can add Python ones also?

**Comment by Ashwani-de** [comment]
Assign me this issue, i will able to add some good question
