### ISSUE TITLE
C++ solution for Problem. 58 in Easy Section

### ISSUE THREAD

**Issue by Shivyoddha** [Vanshika2063/Leetcode-Questions#87]
Hi @Vanshika2063 , 
I would like to add the C++ solution of Problem. 58 of LeetCode.
Could you please assign me with this issue?

**Comment by Vanshika2063** [comment]
sure

**Comment by karti3k** [comment]
i also want to contribute vanshika

**Comment by Vanshika2063** [comment]
> i also want to contribute vanshika

sure
