### ISSUE TITLE
Problem. 69 of Easy Section in CPP

### ISSUE THREAD

**Issue by Shivyoddha** [Vanshika2063/Leetcode-Questions#96]
This issue is about the problem. 69 of easy section in LeetCode
Hi @Vanshika2063 
Could you please assign this issue to me?

**Comment by Vanshika2063** [comment]
sure

**Comment by Shivyoddha** [comment]
Hi @Vanshika2063 ,
could you please review my previous PR ,
without it , it won't be accepted for hacktoberfest
