### ISSUE TITLE
42.Trapping rain water problem on Leetcode

### ISSUE THREAD

**Issue by Siddhesh4501** [Vanshika2063/Leetcode-Questions#98]
Hey i would like to contribute solution of this problem from brute force to most optimal one in c++.
Its Leetcode hard problem.
Can you please assign me this issue ?

**Comment by Vanshika2063** [comment]
sure

**Comment by sahilsharma029** [comment]
Hello! I would like to solve this issue can you please assign me this issue?
and also accept it and add a label tag of hactoberfest accepted. please

**Comment by Vanshika2063** [comment]
> Hello! I would like to solve this issue can you please assign me this issue? and also accept it and add a label tag of hactoberfest accepted. please

do it but in other language

**Comment by sahilsharma029** [comment]
please assign me
